<a href="https://colab.research.google.com/github/asanam767/CODSOFT/blob/main/Customer_Churn_Production.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NAME - Katta Manasa Machine Learning INTERNSHIP @ CODSOFT  TASK 3**

**PROJECT NAME - Customer Churn Prediction**

**GITHUB LINK**: [https://github.com/asanam767/CODSOFT](https://github.com/asanam767/CODSOFT)

---

**Problem Statement:**

Develop a model to predict customer churn for a subscription-based service or business. Use historical customer data, including features like usage behavior and customer demographics, and try algorithms like Logistic Regression, Random Forests, or Gradient Boosting to predict churn.

In [2]:
import numpy as np
import pandas as pd

In [3]:
db=pd.read_csv("/content/Churn_Modelling.csv")

In [4]:
db

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [5]:
db=db.drop(columns=["RowNumber","CustomerId","Surname"])

In [6]:
db

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [7]:
db.columns

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')

In [8]:
columns_to_be_encoded=["Geography","Gender"]

In [9]:
from sklearn.preprocessing import OneHotEncoder
X = db[columns_to_be_encoded]
encoder = OneHotEncoder()
X_encoded = encoder.fit_transform(X)
X_encoded = pd.DataFrame(X_encoded.toarray(), columns=encoder.get_feature_names_out(columns_to_be_encoded))
db_with_encoded = pd.concat([db, X_encoded], axis=1)

In [10]:
db_with_encoded=db_with_encoded.drop(columns=["Geography","Gender"])

In [11]:
db_with_encoded

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0,1.0,0.0
1,608,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0,1.0,0.0
2,502,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0,1.0,0.0
3,699,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0,1.0,0.0
4,850,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0,0.0,1.0
9996,516,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0,0.0,1.0
9997,709,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0,1.0,0.0
9998,772,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0,0.0,1.0
9999,792,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0,1.0,0.0

In [12]:
X=db_with_encoded.drop(columns=["Exited"])
y=db_with_encoded["Exited"]

In [13]:
from sklearn.linear_model import LogisticRegression
my_model=LogisticRegression(random_state=42)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [14]:
my_model.fit(X_train,y_train)

LogisticRegression(random_state=42)

In [15]:
from sklearn.metrics import accuracy_score
y_predict=my_model.predict(X_test)
accuracy = accuracy_score(y_test, y_predict)
print(f"Accuracy: {accuracy*100}%")

Accuracy: 80.05%

In [16]:
from xgboost import XGBClassifier
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
my_model_2=XGBClassifier()
my_model_2.fit(X_train,y_train)
y_predict=my_model_2.predict(X_test)
accuracy = accuracy_score(y_test, y_predict)
print(f"Accuracy: {accuracy*100}%")

Accuracy: 86.25%

In [17]:
final_model=my_model_2